### ISSUE TITLE
Adding rebalance ops

### ISSUE THREAD

**Issue by neesingh-rh** [srijan-sivakumar/redant#184] opened 2021-04-12 05:44 UTC
Add Rebalance ops to the ops library.

**Comment by srijan-sivakumar** [comment] 2021-04-26 19:55
@neesingh-rh I'm closing this issue. We can take it up when we are going to add rebalance related ops. For now we have enough issues to track. Also from next time, we should have specific issues wherein we define clearly what the issue is about rather than just saying adding rebalance ops.

**Closed by srijan-sivakumar** 2021-04-26 19:55 UTC
Labels: enhancement
